name: Deploy React App

on:
  push:
    branches: [ main ]

# This block forces GitHub to allow the script to write and create the gh-pages branch
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm install
          npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Keeps your updated Vite folder
          branch: gh-pages
